# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-24 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uai', models.CharField(max_length=8, verbose_name='Unit\xe9 Administrative Immatricul\xe9e')),
                ('institution_name', models.CharField(max_length=255, verbose_name="Nom de l'institution")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
