# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-28 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("django_esidoc", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="ends_at",
            field=models.DateField(null=True, verbose_name="Date de fin d'abonnement"),
        )
    ]
