# Generated by Django 2.2.15 on 2020-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_esidoc', '0006_auto_20200629_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='uai',
            field=models.CharField(max_length=14, verbose_name='Unité Administrative Immatriculée'),
        ),
        migrations.AddConstraint(
            model_name='institution',
            constraint=models.UniqueConstraint(fields=('uai', 'ent'), name='one_uai_per_ent'),
        ),
    ]
