# Generated by Django 2.2.15 on 2021-02-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_esidoc", "0008_auto_20210222_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="ent",
            field=models.CharField(
                choices=[
                    ("ESIDOC", "Esidoc"),
                    ("HDF", "Hauts-de-France"),
                    ("OCCITANIE", "Occitanie"),
                    ("OCCITANIEAGR", "Occitanie lycée agricole"),
                    ("CORRELYCE", "Corrélyce"),
                    ("GMINVENT", "GMInvent"),
                    ("C3RB", "C3rb"),
                ],
                default="ESIDOC",
                max_length=12,
                verbose_name="Environnements Numériques de Travail",
            ),
        ),
    ]
