# Generated by Django 2.2.24 on 2021-06-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_esidoc", "0009_auto_20210222_1558"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="ent",
        ),
    ]
